name: okmsbun_flutter
description: "Package util package that aims to get rid of boilerplate to start the project quickly"
version: 0.0.1
homepage: https://github.com/okmsbun/okmsbun_flutter

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
